### ISSUE TITLE
is_required() fatal error

### ISSUE THREAD

**Issue by flytech01** [kofimokome/cf7-message-filter#18]
PHP Fatal error:  Call to a member function is_required() on array in /var/userdata/web/vakolatwebaruhaz.hu/website/www/wp-content/plugins/cf7-message-filter/includes/CF7MessageFilter.php on line 626

WordPress 4.1.2 verzió
CF7 versio: 4.2.1

HnD

**Comment by kofimokome** [comment]
Thanks. I will look into it

**Comment by kofimokome** [comment]
Please what is your PHP version?

**Comment by kofimokome** [comment]
Please, update to the latest version of contact form 7 ( version 5.5.3 ) and try again.

**Comment by flytech01** [comment]
THX ;)

My solution is wp settings - interaction - comments blacklist
This works in CF7 to
HnD

**Comment by kofimokome** [comment]
Okay. Thanks.
