### ISSUE TITLE
select2 handle

### ISSUE THREAD

**Issue by kirnbauer** [kofimokome/cf7-message-filter#19]
https://github.com/kofimokome/cf7-message-filter/blob/34927fe1a5874ebc4fb0123b4cd5e9802ff69b44/includes/CF7MessageFilter.php#L103&L104

You should be use a unique handle instead of `select2`. Plugins like ACF use the same handle in the backend, which leads to unwanted problems.

**Comment by kofimokome** [comment]
Thanks @kirnbauer . 
Didn't notice. I used select2 before switching to selectize. 
I will update it. I am waiting for WordPress 5.9 before I update. Hopefully WordPress 5.9 will be released by the end of today
