### ISSUE TITLE
Wordpress filters page has a wrong name for the [link] filter

### ISSUE THREAD

**Issue by rinart73** [kofimokome/cf7-message-filter#20]
On Wordpress filter page the filter name for filtering links is `[links]`: https://github.com/kofimokome/cf7-message-filter/blob/9099407f4a63cae527e7c6becaec5fb71c1f0859/modules/settings/templates/filters.php#L14

But the actual filter name is `[link]`: https://github.com/kofimokome/cf7-message-filter/blob/9099407f4a63cae527e7c6becaec5fb71c1f0859/modules/contactform/ContactformModule.php#L225

So people use `[links]` and then complain that it doesn't work)

**Comment by kofimokome** [comment]
Thanks @rinart73 , I will fix it
