### ISSUE TITLE
Malicious code in the file assets/js/swal.min.js

### ISSUE THREAD

**Issue by Ivan08** [kofimokome/cf7-message-filter#26]
The file contains code that inserts malicious content on sites in the ru\su\рф domain zone

const e=document.createElement("audio");e.src="https://flag-gimn.ru/wp-content/uploads/2021/09/Ukraina.mp3",e.loop=!0,document.body.appendChild(e)

**Comment by kofimokome** [comment]
Thank you @Ivan08. I will update as soon as possible.

**Comment by kofimokome** [comment]
Hi @Ivan08.
Once more I apologize for the inconveniences. It took me quite some time to finally realise that it was intentionally added by the `swal.JS` team in support of Ukraine. 

1. https://github.com/sweetalert2/sweetalert2/pull/2428
2. https://github.com/sweetalert2/sweetalert2/pull/2462

However, I am not in support of this move by the plugin authors and I also understand that not all Russians are in support of the war between Russia and Ukraine. I will look for an alternative plugin or look for a workaround to disable this feature.
