### ISSUE TITLE
break missing

### ISSUE THREAD

**Issue by schedulix** [kofimokome/cf7-message-filter#7]
Hi Kofi,

we had a problem with the validation of our contact form.
Sometimes the defined forbidden patterns showed some effect, sometimes not.

We've analyzed the problem and have found out that an "if ($found) { break; }" is missing. 

If you look at the includes/CF7MessageFilter.php file, there is this function textarea_validation_filter($result, $tag) that tests for forbidden patterns.
This function tests for patterns to occur in the entered text. The entered text is split into words (line 359) and for each word the list of patterns is tested. If some pattern matches, the loop over the list of patterns is terminated, but the loop over the words in the current field is not! Thus if a second word is present that doesn't match, the $found variable is reset to false and the entered text is regarded valid.

If you add a

if ($found) {
   break;
}

on line 406, the loop over the list of words is terminated as well, and the entered text will be regarded invalid as soon as a match is found.
If the entered text happens to consist of a single word or if the last word matches, things work.

Best regards,

Ronald

**Comment by kofimokome** [comment]
thank you @schedulix 
Another person also had the same issue.
I have fixed the issue.
Instead of having two break statements, I decided to modify the current break statement from `break;` to `break 2;` (line 403), this will end the outer loop
Kindly update to the latest version.

**Comment by schedulix** [comment]
Hi Kofi,

your change is obviously the better one.
I would have proposed it as such, if I would have known the correct syntax in PHP.
Thank you for fixing the issue.

Best regards,

Ronald

-- 
independIT Integrative Technologies GmbH
Bergstrasse 6
86529 Schrobenhausen
Germany
HRB Ingolstadt 101.521
Geschäftsführer:
  Dieter Stubler, Dipl. Inform. (FH)
  Ronald Jeninga, Diplom Mathematiker 

e-mail: ronald.jeninga@independit.de
web: http://www.independit.de
Tel: +49 9129 2969040
GSM: +49 1520 1849816
Fax: +49 8252 9658034
